### ISSUE TITLE
Suggested update to the Install instructions/Readme

### ISSUE THREAD

**Issue by erew123** [kanttouchthis/text_generation_webui_xtts#4]
I noticed a few people are struggling to activate their environment. Turns out there are a couple of files supplied with the Text-Gen-WebUI that specifically start your environment for your OS and unload any other environment you might be in.

![image](https://github.com/kanttouchthis/text_generation_webui_xtts/assets/35898566/c784fbdc-17ad-474b-b240-8fa763b0af1d)

cmd_windows.bat, cmd_linux.sh, cmd_macos.sh and cmd_wsl.bat

It might be worth updating the install readme to tell people to run those, as "conda activate textgen" doesnt work on Windows unless youve manually set up a load of other things in the path!

Also, thanks generally for getting this working!

**Comment by kanttouchthis** [comment]
i installed it manually via conda so i wasn't aware of this, thank you. I added it to the readme
